### ISSUE TITLE
coordinate 2bp shift for some and not for others

### ISSUE THREAD

**Issue by zhangtaowhu** [konstantint/pyliftover#10]
Dear konstantint,

I try to use pyliftover to convert hg19ToRheMac8.over.chain.gz, but got some inconsistent results. 
For example: 
lo.convert_coordinate("chr1",40759231 ,'-')  get the same conversion as webtool
[('chr1', 39616603, '-', 9178768280)]
lo.convert_coordinate('chr1',197073253 ,'-') get the -2bp shift to webtool
[('chr1', 169753455, '+', 3907323613)]
Many thanks!

**Comment by konstantint** [comment]
I suspect you must have tried to post the data to the web tool in the form chr1:A-B. Note that in this case A and B are interpreted as 1-based coordinates with B inclusive (unlike the BED format, where they are 0-based and B is exclusive). PyLiftOver operates in 0-based coordinates only (and does not support ranges). Try entering chr1:197073254-197073254 and you will get chr1:169753456-169753456, which is correct.
Or use the BED format:
![image](https://user-images.githubusercontent.com/220083/58937883-f8670280-8773-11e9-895e-184778893b8c.png)

**Comment by zhangtaowhu** [comment]
Thanks a lot for your kind reply!
Yes, I know the 0/1 based differences. But when using pyliftover to convert hg19ToRheMac8.over.chain.gz,
lo.convert_coordinate("chr1",40759231 ,'-') get
[('chr1', 39616603, '-', 9178768280)]
lo.convert_coordinate('chr1',197073253 ,'-') get 
[('chr1', **169753455**, '+', 3907323613)] 
not [('chr1', **169753457**, '+', 3907323613)]
if all 2bp shift I can adjust. But some are 2bp shift and some are not? What I can do if want to use pyliftover?
Many thanks!

**Comment by konstantint** [comment]
> get [('chr1', 169753455, '+', 3907323613)] not [('chr1', 169753457, '+', 3907323613)]

Perhaps I do not understand the question here. Why would you expect LiftOver (either PyLiftOver or the web-based tool) to produce 169753457, when 169753455 is the correct conversion, performed identically by either tool?

**Comment by zhangtaowhu** [comment]
Sorry for the confusing:
The thing is lo.convert_coordinate("chr1",40759231 ,'-') get[('chr1', 39616603, '-', 9178768280)] , which is same as webtool. So I cannot just simply +2bp for all conversion: some 40759231 doesn't need and some 197073253 need it. Please help me find a way to do it?
Many thanks!

**Comment by konstantint** [comment]
40759231 converts to 39616603,
197073253  converts to 169753455.
You can perform either conversion either via the web tool or using PyLiftover.

I do not understand what +2bp you are talking about.
40759231 + 2bp is not equal to 39616603, for example. The coordinate conversion is performed by consulting a list of block-to-block correspondences stored in the chain file, it is not simply adding some constant number of basepairs.

**Comment by konstantint** [comment]
Just in case, let me repeat that your claim that "webtool converts 197073253 to 169753457 is wrong, if it is what you are talking about. Check my screenshot.

**Comment by zhangtaowhu** [comment]
Thanks a lot ! Get your point of "webtool converts 197073253 to 169753455".
