### ISSUE TITLE
Interesting mapping and re-mapping results. Expert opinion please???

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [konstantint/pyliftover#13]
Hi,
Getting on really well with the tool. Works great.

Having some strange results though. Sometimes when I lift a position from hg19 to hg38 and back again, the position after lift-back is not the same as the input. 

The issues is commented here
https://github.com/openvar/variantValidator/issues/201

Probably not anything your tool is doing wrong, but I'm looking for information. Any ideas?

**Comment by konstantint** [comment]
One reason for why this could be happening is the fact that the mappings are not strictly injective. Consider an example:

```
from pyliftover import LiftOver
lo = LiftOver('hg19', 'hg38')

lo.convert_coordinate('chr1', 96992)
> [('chr1', 96992, '+', 20851231461)]

lo.convert_coordinate('chr2', 243181516)
> [('chr1', 96992, '+', 106697)]
```

Note that the second mapping is much weaker (the last value is some kind of an "alignment score") and the inverse chain does not include that mapping at all (although in principle it could, as the chain file could easily contain multiple corresponding points):
```
lo2 = LiftOver('hg38', 'hg19')
lo2.convert_coordinate('chr1', 96992)
> [('chr1', 96992, '+', 20849626768)]
```
and the chain score value is different.

This apparently has something to do with how the alignments are computed. I'd guess that if there are multiple positions matching in the target genome, the weak ones are removed from the chain file to avoid unnecessary confusion. If there is just one suitable match, it is kept, even if it is the result of a weak (possibly erroneous) alignment.
