### ISSUE TITLE
different hg19 positions map to the same hg38 position

### ISSUE THREAD

**Issue by LuoPangpang** [konstantint/pyliftover#17]
![capture](https://user-images.githubusercontent.com/39048164/234262238-711f3a8f-98d0-4625-8394-5d719123e744.PNG)

I used samtools to count the depth of a bam file (hg19) and needed to lift it over to hg38, then I checked the output and found that two different positions in hg19 seemed to map to a single position in hg38. I also found that chr1:13121929 in hg19 map to the 0 position in 'chr1_KI270766v1_alt', which I suppose is not equivalent to 'chr1'. Your suggestions will be greatly appreciated.

**Comment by konstantint** [comment]
Yes, positions in one reference are not one-to-one with positions in another (note that in your case at least the strand is different though). The `chr1_..._alt`, I would guess, is an alternative haplotype contig that was decided to be moved out of the "main" chromosome sequence for whatever reason. Again, there's nothing unusual that a coordinate that previously mapped to the main sequence was now remapped to an alternative contig.

Intepretation and handling of these reference discrepancies is totally up to you.

**Comment by LuoPangpang** [comment]
Thank you for a kind explanation! I will sum the depth count of the two hg19 positions as the count for the single hg38 position, and ignore those positions mapped to 'chr1_..._alt'.
