### ISSUE TITLE
conversion error from hg19 to hg38 in pyliftover

### ISSUE THREAD

**Issue by Dearwunan** [konstantint/pyliftover#19]
chainfile = 'hg19ToHg38.over.chain.gz'
>>> from pyliftover import LiftOver
>>> lo = LiftOver(chainfile)
>>> lo.convert_coordinate('chr22', 42526579)
[('chr22_KI270928v1_alt', 52918, '+', 15145)]
>>> lo.convert_coordinate('chr22', 42526580)
[('chr22', 42130578, '+', 3231095979)]

Blelow was the result of UCSC liftOver tool.
chr22_KI270928v1_alt	52918	52919

The result of UCSC liftOver tool was right and pyliftover gets wrong.
please fix this, Thanks

**Comment by konstantint** [comment]
Please note that Pyliftover uses 0-based indexing while the liftover tool is 1-based. So far all reported perceived mismatches were related to this aspect.

**Comment by Dearwunan** [comment]
The input file of UCSC liftOver tool is bed file with 0-based indexing. The position of "chr22:42526580" is 0-based indexing.
The result of pyliftover is different from the result of  UCSC liftOver tool.

**Comment by konstantint** [comment]
If I input the zero-based `chr22 42526579 42526579` into the web [LiftOver](https://genome.ucsc.edu/cgi-bin/hgLiftOver) I obtain

`chr22_KI270928v1_alt	52918	52918	chr22:42526580-42526579	1`

This seems to match what you report getting from pyliftover.

Similarly, the result of converting `chr22 42526580 42526580` by the web tool is reported to me as:

`chr22	42130578	42130578	chr22:42526581-42526580	1`

This, again, seems to match what you obtained in the Python version.

If I input `chr22	42130578	42130579`, which I presume you did, I get `chr22_KI270928v1_alt 52918 52919`, which seems to indicate that liftOver is treating the right interval endpoint as exclusive (i.e. it just converted chr22:[42130578, 42130579) to the single position that 42130578 mapped to).

This hypothesis seems to be consistent with what we get if we query `chr22	42130578	42130580`, assuming here that we request conversion of [42130578, 42130580), i.e. [42130578, 42130579]. At this point liftOver reports a `split in new` error message, which indeed matches what we saw when converting two positions individually (one maps to `chr22_KI..`, another to `chr22`).

We get the same error if we try the 1-based format (which is, I believe, always inclusive of both endpoints): `chr22:42526580-42526581` reports a `Split in new` error message.

Hope this helps.
