### ISSUE TITLE
Some incorrect conversions from hg38 to hg19 even on '+' strand

### ISSUE THREAD

**Issue by iljungr** [konstantint/pyliftover#4]
Here are some more discrepancies when converting from hg38 to hg19, even with the result on the '+' strand. ("Should be" means what the ucsc liftover tool reports.)

lo.convert(chr1, 145216150) -> [('chr1', 144341055, '+', 20849626768)], but should be chr1:148176493
lo.convert(chr21, 8217035) -> [('chrUn_gl000220', 116507, '+', 14325956)], but should be chrUn_gl000220:116506
lo.convert(chr13, 71866526) -> [('chr13', 72440664, '+', 9027876266)], but should be chr13:72440658
lo.convert(chr1, 145215978) -> [('chr1', 148176321, '+', 1370413)], but should be chr1:144340883

**Comment by konstantint** [comment]
I believe this has nothing to do with the strand, but probably the same issue as #2 and #3 - something got broken with the new chain files (maybe a format change or the like). But of course, the more test data, the merrier!
