### ISSUE TITLE
convert_coordinate fails with zero-based indices (but unity-based works)

### ISSUE THREAD

**Issue by ofrei** [konstantint/pyliftover#5]
Hi,

I have a list of SNPs in hg18 build, and I'm lifting their CHR:BP into hg19 using pylyftover. I believe my  BP coordinates are unity-based, so I'm expecting that I have to deduct 1 when passing BP to `convert_coordinate` (and do +1 afterwards). However, I found some SNPs that I'm not able to convert this way. If, however, I do not deduct 1, conversion succeeds, and the result is correct (e.g. I'm getting correct hg19 coordinate of the SNP which I can look up in SNPdb). 

Is there a chance that documentation is incorrect and convert_coordinate in fact expects unity-based indices?

My script:
```
from pyliftover import LiftOver
lift = LiftOver('hg18', 'hg19')

# Correct conversion 
print(lift.convert_coordinate('chr2', 1203295)) # rs4971417,    https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=4971417
print(lift.convert_coordinate('chr2', 3495093)) # rs10190397,   https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=10190397
print(lift.convert_coordinate('chr2', 21043693)) # rs6547409,   https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=6547409
print(lift.convert_coordinate('chr2', 21043722)) # rs17041663,  https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=17041663

# Conversion returns None
print(lift.convert_coordinate('chr2', 1203295-1))
print(lift.convert_coordinate('chr2', 3495093-1))
print(lift.convert_coordinate('chr2', 21043693-1))
print(lift.convert_coordinate('chr2', 21043722-1))
```

Output:
```
[('chr2', 1213294, '+', 22466147973)]
[('chr2', 3516085, '+', 22466147973)]
[('chr2', 21190209, '+', 22466147973)]
[('chr2', 21190238, '+', 22466147973)]
[]
[]
[]
[]
```

**Comment by konstantint** [comment]
I am pretty certain that PyLiftover is built around 0-based coordinates - remember writing tests for it myself. Perhaps your SNPs are 0-based as well?

**Comment by ofrei** [comment]
I think my SNPs are 1-base. Otherwise ``lift.convert_coordinate('chr2', 1203295)`` should actually return ``1213293``, not ``1213294``. This is because 1213294 corresponds to unity-based hg19 coordinate for my SNP (which I see from the NCBI browser: https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=4971417 ).

**Comment by konstantint** [comment]
If you go to https://genome.ucsc.edu/cgi-bin/hgLiftOver and paste the following into the corresponding text box
```
chr2 1203295 1203296 A0
chr2 3495093 3495094 B0
#
chr2 1203294 1203295 A1
chr2 3495092 3495093 B1
```
you will get the result which matches what PyLiftOver is doing:
```
chr2	1213294	1213295	A0
chr2	3516085	3516086	B0
```
and failed conversions for `A1` and `B1`.
(Note that LiftOver web is also using 0-based coordinates).

PyLiftOver aims to match what LiftOver is doing here, so either the liftover chain file is somehow wrong for this coordinate, or perhaps your original SNP coordinates are indeed 0-based, or there is some other error somewhere.

**Comment by ofrei** [comment]
I agree, this is a strange behavior but not a bug, as long as pyliftover is consistent with the LiftOver. Closing the ticket.
P.S. Found a nice post named *Tutorial: Cheat Sheet For One-Based Vs Zero-Based Coordinate Systems* here https://www.biostars.org/p/84686/ . Tricky stuff...
