### ISSUE TITLE
Deprecation warning - urlopen

### ISSUE THREAD

**Issue by TeriForey** [konstantint/pyliftover#7]
Pyliftover version 0.3 (installed via pip) on Python 3.6.8 I get the following warning:
```
.../lib/python3.6/site-packages/pyliftover/chainfile.py:26: DeprecationWarning: ErrorAwareURLOpener style of invoking requests is deprecated. Use newer urlopen functions/methods
    _urlopener = ErrorAwareURLOpener()
```

Doesn't seem to be causing any major problems but an update to remove the warning would be appreciated. Thank you

**Comment by konstantint** [comment]
Fixed in 0.4
